// swift-tools-version: 5.10
// The swift-tools-version declares the minimum version of Swift required to build this package.

import PackageDescription

let package = Package(
    name: "SVGUIView",
    platforms: [
        .iOS(.v16),
    ],
    products: [
        .library(
            name: "SVGUIView",
            targets: ["SVGUIView"]
        ),
        .library(
            name: "SVGView",
            targets: ["SVGView"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/nicklockwood/SwiftFormat", exact: "0.51.2"),
    ],
    targets: [
        .target(name: "_SPI", swiftSettings: [
            .enableUpcomingFeature("ConciseMagicFile"),
            .enableUpcomingFeature("ForwardTrailingClosures"),
            .enableUpcomingFeature("ExistentialAny"),
            .enableUpcomingFeature("StrictConcurrency"),
            .enableUpcomingFeature("ImplicitOpenExistentials"),
            .enableUpcomingFeature("BareSlashRegexLiterals"),
            .enableUpcomingFeature("DeprecateApplicationMain"),
            .enableUpcomingFeature("ImportObjcForwardDeclarations"),
            .enableUpcomingFeature("DisableOutwardActorInference"),
            .enableUpcomingFeature("InternalImportsByDefault"),
            .enableUpcomingFeature("IsolatedDefaultValues"),
            .enableUpcomingFeature("GlobalConcurrency"),
            .enableUpcomingFeature("RegionBasedIsolation"),
            .enableUpcomingFeature("InferSendableFromCaptures"),
            .enableUpcomingFeature("DynamicActorIsolation"),
            .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
            .enableUpcomingFeature("MemberImportVisibility"),
            .enableUpcomingFeature("NonescapableTypes"),
            .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
            .enableUpcomingFeature("InferIsolatedConformances"),
            .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
            .enableUpcomingFeature("InferIsolatedConformances"),
        ]),
        .target(name: "_ICU", swiftSettings: [
            .enableUpcomingFeature("ConciseMagicFile"),
            .enableUpcomingFeature("ForwardTrailingClosures"),
            .enableUpcomingFeature("ExistentialAny"),
            .enableUpcomingFeature("StrictConcurrency"),
            .enableUpcomingFeature("ImplicitOpenExistentials"),
            .enableUpcomingFeature("BareSlashRegexLiterals"),
            .enableUpcomingFeature("DeprecateApplicationMain"),
            .enableUpcomingFeature("ImportObjcForwardDeclarations"),
            .enableUpcomingFeature("DisableOutwardActorInference"),
            .enableUpcomingFeature("InternalImportsByDefault"),
            .enableUpcomingFeature("IsolatedDefaultValues"),
            .enableUpcomingFeature("GlobalConcurrency"),
            .enableUpcomingFeature("RegionBasedIsolation"),
            .enableUpcomingFeature("InferSendableFromCaptures"),
            .enableUpcomingFeature("DynamicActorIsolation"),
            .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
            .enableUpcomingFeature("MemberImportVisibility"),
            .enableUpcomingFeature("NonescapableTypes"),
            .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
            .enableUpcomingFeature("InferIsolatedConformances"),
            .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
            .enableUpcomingFeature("InferIsolatedConformances"),
        ]),
        .target(name: "_CShims", swiftSettings: [
            .enableUpcomingFeature("ConciseMagicFile"),
            .enableUpcomingFeature("ForwardTrailingClosures"),
            .enableUpcomingFeature("ExistentialAny"),
            .enableUpcomingFeature("StrictConcurrency"),
            .enableUpcomingFeature("ImplicitOpenExistentials"),
            .enableUpcomingFeature("BareSlashRegexLiterals"),
            .enableUpcomingFeature("DeprecateApplicationMain"),
            .enableUpcomingFeature("ImportObjcForwardDeclarations"),
            .enableUpcomingFeature("DisableOutwardActorInference"),
            .enableUpcomingFeature("InternalImportsByDefault"),
            .enableUpcomingFeature("IsolatedDefaultValues"),
            .enableUpcomingFeature("GlobalConcurrency"),
            .enableUpcomingFeature("RegionBasedIsolation"),
            .enableUpcomingFeature("InferSendableFromCaptures"),
            .enableUpcomingFeature("DynamicActorIsolation"),
            .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
            .enableUpcomingFeature("MemberImportVisibility"),
            .enableUpcomingFeature("NonescapableTypes"),
            .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
            .enableUpcomingFeature("InferIsolatedConformances"),
            .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
            .enableUpcomingFeature("InferIsolatedConformances"),
        ]),
        .target(
            name: "SVGUIView",
            dependencies: ["_SPI", "_ICU", "_CShims"],
            swiftSettings: [
                .enableUpcomingFeature("ConciseMagicFile"),
                .enableUpcomingFeature("ForwardTrailingClosures"),
                .enableUpcomingFeature("ExistentialAny"),
                // .enableUpcomingFeature("StrictConcurrency"),
                .enableUpcomingFeature("ImplicitOpenExistentials"),
                .enableUpcomingFeature("BareSlashRegexLiterals"),
                .enableUpcomingFeature("DeprecateApplicationMain"),
                .enableUpcomingFeature("ImportObjcForwardDeclarations"),
                .enableUpcomingFeature("DisableOutwardActorInference"),
                .enableUpcomingFeature("InternalImportsByDefault"),
                .enableUpcomingFeature("IsolatedDefaultValues"),
                // .enableUpcomingFeature("GlobalConcurrency"),
                // .enableUpcomingFeature("RegionBasedIsolation"),
                .enableUpcomingFeature("InferSendableFromCaptures"),
                .enableUpcomingFeature("DynamicActorIsolation"),
                .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
                // .enableUpcomingFeature("MemberImportVisibility"),
                .enableUpcomingFeature("NonescapableTypes"),
                // .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
                .enableUpcomingFeature("InferIsolatedConformances"),
                .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
                // .enableUpcomingFeature("InferIsolatedConformances"),
            ]
        ),
        .target(
            name: "SVGView",
            dependencies: ["SVGUIView"],
            swiftSettings: [
                .enableUpcomingFeature("ConciseMagicFile"),
                .enableUpcomingFeature("ForwardTrailingClosures"),
                .enableUpcomingFeature("ExistentialAny"),
                .enableUpcomingFeature("StrictConcurrency"),
                .enableUpcomingFeature("ImplicitOpenExistentials"),
                .enableUpcomingFeature("BareSlashRegexLiterals"),
                .enableUpcomingFeature("DeprecateApplicationMain"),
                .enableUpcomingFeature("ImportObjcForwardDeclarations"),
                .enableUpcomingFeature("DisableOutwardActorInference"),
                .enableUpcomingFeature("InternalImportsByDefault"),
                .enableUpcomingFeature("IsolatedDefaultValues"),
                .enableUpcomingFeature("GlobalConcurrency"),
                .enableUpcomingFeature("RegionBasedIsolation"),
                .enableUpcomingFeature("InferSendableFromCaptures"),
                .enableUpcomingFeature("DynamicActorIsolation"),
                .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
                .enableUpcomingFeature("MemberImportVisibility"),
                .enableUpcomingFeature("NonescapableTypes"),
                .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
                .enableUpcomingFeature("InferIsolatedConformances"),
                .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
                .enableUpcomingFeature("InferIsolatedConformances"),
            ]
        ),
        .testTarget(
            name: "SVGUIViewTests",
            dependencies: ["SVGUIView"],
            resources: [.process("assets")],
            swiftSettings: [
                .enableUpcomingFeature("ConciseMagicFile"),
                .enableUpcomingFeature("ForwardTrailingClosures"),
                .enableUpcomingFeature("ExistentialAny"),
                .enableUpcomingFeature("StrictConcurrency"),
                .enableUpcomingFeature("ImplicitOpenExistentials"),
                .enableUpcomingFeature("BareSlashRegexLiterals"),
                .enableUpcomingFeature("DeprecateApplicationMain"),
                .enableUpcomingFeature("ImportObjcForwardDeclarations"),
                .enableUpcomingFeature("DisableOutwardActorInference"),
                .enableUpcomingFeature("InternalImportsByDefault"),
                .enableUpcomingFeature("IsolatedDefaultValues"),
                .enableUpcomingFeature("GlobalConcurrency"),
                .enableUpcomingFeature("RegionBasedIsolation"),
                .enableUpcomingFeature("InferSendableFromCaptures"),
                .enableUpcomingFeature("DynamicActorIsolation"),
                .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
                .enableUpcomingFeature("MemberImportVisibility"),
                .enableUpcomingFeature("NonescapableTypes"),
                .enableUpcomingFeature("NonisolatedNonsendingByDefault"),
                .enableUpcomingFeature("InferIsolatedConformances"),
                .enableUpcomingFeature("GlobalActorIsolatedTypesUsability"),
                .enableUpcomingFeature("InferIsolatedConformances"),
            ]
        ),
    ]
)

